DATASET = [
    # MYTHS (Common Misconceptions & False Claims)
    ("Eating carrots always gives you perfect night vision.", "Myth"),
    ("You must drink exactly eight glasses of water every day.", "Myth"),
    ("Everyone says cracking knuckles causes arthritis.", "Myth"),
    ("If you swallow gum, it stays in your stomach for seven years.", "Myth"),
    ("Cold weather always causes colds.", "Myth"),
    ("Humans use only 10 percent of their brain.", "Myth"),
    ("Vaccines always cause severe side effects.", "Myth"),
    ("You can catch a cold by going outside with wet hair.", "Myth"),
    ("Sugar makes children permanently hyperactive.", "Myth"),
    ("Microwave food has no nutrition left.", "Myth"),
    ("Detox teas remove all toxins from your body overnight.", "Myth"),
    ("Everyone must avoid all fats to stay healthy.", "Myth"),
    ("Reading in dim light permanently damages your eyes.", "Myth"),
    ("You should never wake a sleepwalker.", "Myth"),
    ("Natural products are always safe.", "Myth"),
    ("All bacteria are bad for humans.", "Myth"),
    ("Hair and nails keep growing after death.", "Myth"),
    ("People lose most body heat through the head alone.", "Myth"),
    ("Bulls get angry when they see the color red.", "Myth"),
    ("Lightning never strikes the same place twice.", "Myth"),
    ("You swallow eight spiders a year in your sleep.", "Myth"),
    ("Goldfish have a three-second memory.", "Myth"),
    ("Shaving hair makes it grow back thicker and darker.", "Myth"),
    ("Touching a toad will give you warts.", "Myth"),
    ("Bats are completely blind.", "Myth"),
    ("You should wait an hour after eating before swimming.", "Myth"),
    ("Vikings wore horned helmets.", "Myth"),
    ("Dogs only see in black and white.", "Myth"),
    ("Ostriches bury their heads in the sand when scared.", "Myth"),
    ("Napoleon Bonaparte was extremely short.", "Myth"),
    ("We only have five senses.", "Myth"),
    ("Chameleons change color to blend in with their surroundings.", "Myth"),
    ("Different parts of the tongue taste different things.", "Myth"),
    ("Alcohol keeps you warm in cold weather.", "Myth"),
    ("A penny dropped from the Empire State Building can kill you.", "Myth"),
    ("Elephants are afraid of mice.", "Myth"),
    ("There are 13 months in a year.", "Myth"),
    ("There are 8 days in a week.", "Myth"),
    ("The earth is flat.", "Myth"),
    ("Space is completely devoid of gravity.", "Myth"),
    ("Antibiotics can cure the common cold or flu.", "Myth"),
    ("Dinosaurs and humans coexisted.", "Myth"),
    ("Mount Everest is the tallest mountain in the solar system.", "Myth"),
    ("Blood in your veins is blue until it hits oxygen.", "Myth"),
    ("The Great Wall of China is the only man-made object visible from space.", "Myth"),
    ("A dog's mouth is cleaner than a human's.", "Myth"),
    ("Dropping a coin from a tall building will kill a pedestrian.", "Myth"),
    ("Sugar causes diabetes directly.", "Myth"),
    ("Einstein failed math in school.", "Myth"),
    ("Humans evolved from monkeys.", "Myth"),
    ("Milk increases mucus production.", "Myth"),
    ("Swallowing watermelon seeds will grow a watermelon in your stomach.", "Myth"),
    ("Rusty nails cause tetanus directly.", "Myth"),
    ("Cracking your back too much will paralyze you.", "Myth"),
    ("Going out in the cold with wet hair will give you pneumonia.", "Myth"),
    ("Swallowing gum takes seven years to digest.", "Myth"),
    ("Lightning never hits the same place twice.", "Myth"),
    ("The Great Wall of China is visible from the Moon.", "Myth"),
    ("Shaving hair makes it grow back thicker.", "Myth"),
    ("You only use ten percent of your brain.", "Myth"),
    ("Cracking your knuckles causes arthritis.", "Myth"),
    ("Waking a sleepwalker causes a heart attack.", "Myth"),
    ("A duck's quack doesn't echo.", "Myth"),
    ("Glass is a slow-moving liquid.", "Myth"),
    ("An earthworm becomes two worms if cut in half.", "Myth"),
    ("The tongue map shows different taste areas.", "Myth"),
    ("Wait an hour after eating before you swim.", "Myth"),
    ("Toilet flushes spin in the opposite direction in the southern hemisphere.", "Myth"),
    ("Houseflies only live for 24 hours.", "Myth"),
    ("Goldfish have a memory of 3 seconds.", "Myth"),
    ("Ostriches stick their heads in the sand.", "Myth"),
    ("Humans only have 5 senses.", "Myth"),
    ("Sugar makes kids hyper.", "Myth"),
    ("Sunflowers follow the sun across the sky all day.", "Myth"),
    ("Poinsettias are deadly poisonous.", "Myth"),
    ("Dogs see only in black and white.", "Myth"),
    ("Lemmings jump off clips to their deaths.", "Myth"),
    ("Bats are blind.", "Myth"),
    ("Sharks can smell a single drop of blood from miles away.", "Myth"),
    ("Earth is closer to the sun in summer.", "Myth"),
    ("The North Star is the brightest star in the sky.", "Myth"),
    ("Sunburn can be cured with butter.", "Myth"),
    ("Tetanus only comes from rusty nails.", "Myth"),
    ("A fan in a closed room can cause death.", "Myth"),
    ("Reading in the dark ruins your eyes.", "Myth"),
    ("The moon has a dark side that never sees sunlight.", "Myth"),
    ("Hair and nails grow after you die.", "Myth"),
    ("Toads give you warts.", "Myth"),
    ("You swallow eight spiders a year while sleeping.", "Myth"),
    ("Bulls hate red.", "Myth"),
    ("Lightning doesn't strike twice.", "Myth"),
    ("Bananas grow on trees.", "Myth"),
    ("Tomatoes are vegetables.", "Myth"),
    ("Peanuts are nuts.", "Myth"),
    ("Strawberries are berries.", "Myth"),
    ("Mice love cheese.", "Myth"),
    ("Poison ivy rash is contagious.", "Myth"),
    ("Coffee dehydrates you.", "Myth"),
    ("Blood is blue inside the body.", "Myth"),
    ("The 5-second rule is safe for food.", "Myth"),
    ("Humans only use 10% of their brains.", "Myth"),
    ("Cracking knuckles leads to arthritis.", "Myth"),
    ("Dogs see in black and white.", "Myth"),
    ("Ostriches bury their heads in sand.", "Myth"),
    ("Vikings wore horned helmets.", "Myth"),
    ("Napolean was very short.", "Myth"),
    ("Bats are blind creatures.", "Myth"),
    ("A penny dropped from a skyscraper can kill.", "Myth"),
    ("Glass is a liquid.", "Myth"),
    ("Bananas grow on trees naturally.", "Myth"),
    ("Sugar causes hyperactivity in children.", "Myth"),
    ("Coffee is made from beans.", "Myth"),
    ("Humans have only five senses.", "Myth"),
    ("Sunflowers follow the sun.", "Myth"),
    ("Mice love cheese above all else.", "Myth"),
    ("Sharks don't get cancer.", "Myth"),
    ("Lightning never strikes twice in one spot.", "Myth"),
    ("Goldfish have a 3-second memory span.", "Myth"),
    ("Chameleons change color for camouflage.", "Myth"),
    ("The tongue has different taste zones.", "Myth"),
    ("Eating after 8 PM makes you gain weight.", "Myth"),
    ("Drinking fruit juice is just as healthy as eating fruit.", "Myth"),
    ("Stretching before exercise prevents injury.", "Myth"),
    ("Detox diets are necessary to remove toxins.", "Myth"),
    ("Organic food is always more nutritious than non-organic food.", "Myth"),
    ("Your metabolism slows down as you age.", "Myth"),
    ("Cardio is the only way to lose weight.", "Myth"),
    ("You can target fat loss in specific areas of the body.", "Myth"),
    ("Supplements are necessary for a healthy diet.", "Myth"),
    ("Fasting is bad for your health.", "Myth"),
    ("All fats are unhealthy.", "Myth"),
    ("Gluten is bad for everyone.", "Myth"),
    ("You need to eat small meals throughout the day to lose weight.", "Myth"),
    ("Dairy is the only source of calcium.", "Myth"),
    ("Drinking water with meals dilutes digestive juices.", "Myth"),
    ("Brown sugar is healthier than white sugar.", "Myth"),
    ("A high-protein diet is bad for your kidneys.", "Myth"),
    ("You can't get enough protein on a plant-based diet.", "Myth"),
    ("Frozen vegetables are less nutritious than fresh ones.", "Myth"),
    ("Skipping breakfast is bad for your metabolism.", "Myth"),
    ("Eating fat makes you fat.", "Myth"),
    ("Fruit has too much sugar and should be avoided.", "Myth"),
    ("You should avoid all processed foods.", "Myth"),
    ("Eggs are bad for your heart.", "Myth"),
    ("Red meat causes cancer.", "Myth"),
    ("Eating too much salt causes high blood pressure.", "Myth"),
    ("Natural sweeteners are better for you than white sugar.", "Myth"),
    ("Weight loss is all about calories in versus calories out.", "Myth"),
    ("You can lose weight by eating certain fat-burning foods.", "Myth"),
    ("Drinking lemon water in the morning boosts your metabolism.", "Myth"),

    # FACTS (Verified Scientific Truths)
    ("The Earth revolves around the Sun.", "Fact"),
    ("Regular exercise helps improve heart health.", "Fact"),
    ("Vaccines help the immune system prevent many diseases.", "Fact"),
    ("Boiling water can kill many harmful microbes.", "Fact"),
    ("Sleep is important for memory and concentration.", "Fact"),
    ("Smoking increases the risk of lung disease.", "Fact"),
    ("Handwashing with soap reduces infection spread.", "Fact"),
    ("Plants need sunlight for photosynthesis.", "Fact"),
    ("The human body needs vitamins and minerals.", "Fact"),
    ("A balanced diet supports overall health.", "Fact"),
    ("Antibiotics do not work against viruses.", "Fact"),
    ("Climate change is linked to rising global temperatures.", "Fact"),
    ("The Pacific Ocean is larger than the Indian Ocean.", "Fact"),
    ("DNA carries genetic information in living organisms.", "Fact"),
    ("The boiling point of water is about 100C at sea level.", "Fact"),
    ("Blood carries oxygen through the body.", "Fact"),
    ("The heart is a muscular organ.", "Fact"),
    ("Satellites orbit around planets due to gravity.", "Fact"),
    ("Water freezes at 0 degrees Celsius.", "Fact"),
    ("The Earth has one natural satellite, the Moon.", "Fact"),
    ("Alexander Fleming discovered penicillin.", "Fact"),
    ("The Great Wall of China is the longest wall in the world.", "Fact"),
    ("The Amazon River is the second longest river in the world.", "Fact"),
    ("Mount Everest is the highest mountain on Earth.", "Fact"),
    ("The human skeleton is made up of 206 bones in adults.", "Fact"),
    ("Light travels faster than sound.", "Fact"),
    ("Jupiter is the largest planet in our solar system.", "Fact"),
    ("Oxygen is essential for human respiration.", "Fact"),
    ("The capital of Australia is Canberra.", "Fact"),
    ("Diamonds are made of carbon.", "Fact"),
    ("An octopus has three hearts.", "Fact"),
    ("Honey never spoils.", "Fact"),
    ("Bananas are internally classified as berries.", "Fact"),
    ("The Sahara is the largest hot desert in the world.", "Fact"),
    ("Sound cannot travel through a vacuum.", "Fact"),
    ("The human brain consumes about 20% of the body's energy.", "Fact"),
    ("Water is made of two hydrogen atoms and one oxygen atom.", "Fact"),
    ("There are 7 days in a week.", "Fact"),
    ("A triangle has three sides.", "Fact"),
    ("The sun rises in the east and sets in the west.", "Fact"),
    ("Ice is solid water.", "Fact"),
    ("Humans breathe oxygen.", "Fact"),
    ("A year has 12 months.", "Fact"),
    ("Fish live in water.", "Fact"),
    ("The sky appears blue during a clear day.", "Fact"),
    ("Gravity pulls objects toward the center of the Earth.", "Fact"),
    ("Photosynthesis produces oxygen as a byproduct.", "Fact"),
    ("Whales are mammals.", "Fact"),
    ("Spiders have eight legs.", "Fact"),
    ("The Milky Way is a spiral galaxy.", "Fact"),
    ("Cheetahs are the fastest land animals.", "Fact"),
    ("Birds have feathers.", "Fact"),
    ("The Eiffel Tower is located in Paris.", "Fact"),
    ("Tokyo is the capital of Japan.", "Fact"),
    ("Friction opposes motion.", "Fact"),
    ("Magnets have north and south poles.", "Fact"),
    ("Sharks have cartilaginous skeletons.", "Fact"),
    ("Grass contains chlorophyll.", "Fact"),
    ("The heart pumps blood.", "Fact"),
    ("Humans have five basic senses.", "Fact"),
    ("Bees produce honey.", "Fact"),
    ("Computers process data.", "Fact"),
    ("Trees produce oxygen.", "Fact"),
    ("Fire requires oxygen.", "Fact"),
    ("An hour has 60 minutes.", "Fact"),
    ("A minute has 60 seconds.", "Fact"),
    ("The Nile is a long river.", "Fact"),
    ("Antarctica is a cold continent.", "Fact"),
    ("Steel is an alloy.", "Fact"),
    ("Paper is made from wood.", "Fact"),
    ("Glass is made from sand.", "Fact"),
    ("The moon affects tides.", "Fact"),
    ("Eagles are predators.", "Fact"),
    ("The brain controls the body.", "Fact"),
    ("Venus is the hottest planet in our solar system.", "Fact"),
    ("Saturn has a massive ring system.", "Fact"),
    ("Mars is known as the Red Planet.", "Fact"),
    ("The sun is a star.", "Fact"),
    ("Protons have a positive charge.", "Fact"),
    ("Neutrons have no charge.", "Fact"),
    ("Electrons have a negative charge.", "Fact"),
    ("Sound travels faster in water than in air.", "Fact"),
    ("Light is both a particle and a wave.", "Fact"),
    ("The speed of light is roughly 300,000 km/s.", "Fact"),
    ("Helium is lighter than air.", "Fact"),
    ("Mercury is the closest planet to the sun.", "Fact"),
    ("Pluto is classified as a dwarf planet.", "Fact"),
    ("A rectangle has four sides.", "Fact"),
    ("A square has four equal sides.", "Fact"),
    ("Mammals nurse their young with milk.", "Fact"),
    ("Reptiles are cold-blooded.", "Fact"),
    ("Amphibians can live on land and in water.", "Fact"),
    ("The ostrich is the largest bird.", "Fact"),
    ("The blue whale is the largest animal ever.", "Fact"),
    ("Hummingbirds can fly backwards.", "Fact"),
    ("Honeybees can fly.", "Fact"),
    ("Water is essential for life.", "Fact"),
    ("The brain is in the head.", "Fact"),
    ("Apples grow on trees.", "Fact"),
    ("Clouds are made of water.", "Fact"),
    ("The ocean is salty.", "Fact"),
    ("Wood comes from trees.", "Fact"),
    ("Iron is a metal.", "Fact"),
    ("The moon orbits the earth.", "Fact"),
    ("Stars are far away.", "Fact"),
    ("Diamonds are very hard.", "Fact"),
    ("Rain comes from clouds.", "Fact"),
    ("A healthy diet includes a variety of nutrients.", "Fact"),
    ("Regular physical activity is beneficial for weight management.", "Fact"),
    ("Adequate sleep is crucial for overall health.", "Fact"),
    ("Hydration is important for bodily functions.", "Fact"),
    ("Mental health is as important as physical health.", "Fact"),
    ("Fiber aids in digestion.", "Fact"),
    ("Protein is essential for muscle repair.", "Fact"),
    ("Antioxidants help protect cells from damage.", "Fact"),
    ("A balanced diet includes fruits and vegetables.", "Fact"),
    ("Limiting processed foods is generally recommended for health.", "Fact"),
    ("Chronic stress can negatively impact health.", "Fact"),
    ("Social connections contribute to well-being.", "Fact"),
    ("Proper hygiene reduces the risk of illness.", "Fact"),
    ("Regular check-ups can help prevent certain diseases.", "Fact"),
    ("Sunlight is a source of Vitamin D.", "Fact"),
    ("Healthy habits are easier to maintain when they're enjoyable.", "Fact"),
    ("Consistency is key to seeing results from exercise.", "Fact"),
    ("Small changes can lead to significant long-term health benefits.", "Fact"),
    ("Mindfulness can help reduce stress and improve focus.", "Fact"),
    ("A supportive environment can make a difference in achieving health goals.", "Fact"),

    # UNCERTAIN (Opinions, Future Predictions, or Debatable Claims)
    ("This herbal drink might improve memory for some people.", "Uncertain"),
    ("Scientists are still studying the long-term effects of this diet.", "Uncertain"),
    ("It could be helpful, but evidence is currently limited.", "Uncertain"),
    ("Some people report benefits, though results are mixed.", "Uncertain"),
    ("This claim may be true in specific situations.", "Uncertain"),
    ("There is not enough data to confirm this yet.", "Uncertain"),
    ("The study suggests a possible link, not a final conclusion.", "Uncertain"),
    ("Experts disagree on whether this method works.", "Uncertain"),
    ("Initial research is promising but inconclusive.", "Uncertain"),
    ("This treatment may help, depending on individual conditions.", "Uncertain"),
    ("The evidence is weak and more trials are needed.", "Uncertain"),
    ("It is difficult to say if this is always effective.", "Uncertain"),
    ("This statement can be context-dependent.", "Uncertain"),
    ("The current findings are not definitive.", "Uncertain"),
    ("Researchers have not reached a consensus yet.", "Uncertain"),
    ("The available reports are contradictory.", "Uncertain"),
    ("There may be bias in these observations.", "Uncertain"),
    ("Results vary across different age groups.", "Uncertain"),
    ("Artificial general intelligence will be achieved by 2030.", "Uncertain"),
    ("There is life on other planets, though we have not found it yet.", "Uncertain"),
    ("Eating chocolate every day increases your lifespan.", "Uncertain"),
    ("Drinking a specific tea guarantees weight loss.", "Uncertain"),
    ("This new supplement cures all types of pain.", "Uncertain"),
    ("The stock market will crash next week.", "Uncertain"),
    ("It will definitely rain exactly at 3:00 PM tomorrow in London.", "Uncertain"),
    ("Red wine is always good for the heart.", "Uncertain"),
    ("A certain crypto coin will replace all fiat currency by next year.", "Uncertain"),
    ("String theory is the only correct physical model of the universe.", "Uncertain"),
    ("We will eventually be able to upload human consciousness to computers.", "Uncertain"),
    ("This specific superfood will prevent cancer.", "Uncertain"),
    ("Dark matter is made of undiscovered particles.", "Uncertain"),
    ("Time travel will be invented in the far future.", "Uncertain"),
    ("Using this brand of shampoo guarantees baldness cure.", "Uncertain"),
    ("Everyone needs an afternoon nap to be productive.", "Uncertain"),
    ("There are parallel universes identical to ours.", "Uncertain"),
    ("Dreaming about falling means you are failing in life.", "Uncertain"),
    ("A new technology will completely reverse aging in humans.", "Uncertain"),
    ("Extraterrestrials have visited Earth in ancient times.", "Uncertain"),
    ("Coffee is entirely bad for you.", "Uncertain"),
    ("The next major earthquake will happen within 5 years.", "Uncertain"),
    ("Using cellphones causes brain cancer.", "Uncertain"),
    ("Humans will establish a colony on Mars by 2040.", "Uncertain"),
    ("Eating after 8 PM directly causes weight gain.", "Uncertain"),
    ("Virtual reality will replace all physical screens.", "Uncertain"),
    ("Teleportation will become a reality for human transport.", "Uncertain"),
    ("A global pandemic will happen every decade from now on.", "Uncertain"),
    ("Meditation alone can cure clinical depression.", "Uncertain"),
    ("The lost city of Atlantis will be discovered in the Atlantic Ocean.", "Uncertain"),
    ("Curing the common cold is scientifically impossible.", "Uncertain"),
    ("Some people believe ghosts are real but there's no proof.", "Uncertain"),
    ("Aliens might have built the pyramids.", "Uncertain"),
    ("Crystals can heal physical illnesses.", "Uncertain"),
    ("The Loch Ness Monster exists.", "Uncertain"),
    ("Bigfoot is real.", "Uncertain"),
    ("Predictions from horoscopes are accurate.", "Uncertain"),
    ("Feng shui can bring wealth.", "Uncertain"),
    ("Magnet therapy works for arthritis.", "Uncertain"),
    ("Homeopathy is as effective as conventional medicine.", "Uncertain"),
    ("Ancient astronauts visited Earth.", "Uncertain"),
    ("The world will end in 2050.", "Uncertain"),
    ("Social media is destroying human attention spans.", "Uncertain"),
    ("Life in the city is better than life in the countryside.", "Uncertain"),
    ("Artificial intelligence will eventually replace all human artists.", "Uncertain"),
    ("The secret to happiness is simplicity.", "Uncertain"),
    ("Remote work is more productive than office work.", "Uncertain"),
    ("The universal basic income is the only solution to automation.", "Uncertain"),
    ("Personalized medicine will make hospitals obsolete.", "Uncertain"),
    ("Quantum computers will break all current encryption within ten years.", "Uncertain"),
    ("Deep-sea exploration is more important than space exploration.", "Uncertain"),
    ("Genetically modified foods are the only way to feed the world.", "Uncertain"),
    ("Cryptocurrency is the future of finance.", "Uncertain"),
    ("Electric cars will replace gas cars by 2035.", "Uncertain"),
    ("Mars was once covered in water.", "Uncertain"),
    ("Colonizing the moon is feasible.", "Uncertain"),
    ("Nanotechnology will cure all diseases.", "Uncertain"),
    ("The universe will end in a Big Rip.", "Uncertain"),
    ("Parallel universes interact with ours.", "Uncertain"),
    ("Brain implants will enhance human intelligence.", "Uncertain"),
    ("Nuclear fusion will provide unlimited energy soon.", "Uncertain"),
    ("Gene editing will eliminate all genetic disorders.", "Uncertain"),
    ("The concept of retirement will change significantly.", "Uncertain"),
    ("Privacy will be non-existent in the future.", "Uncertain"),
    ("Sustainability will be the primary driver of the global economy.", "Uncertain"),
    ("Education will be completely transformed by technology.", "Uncertain"),
    ("The definition of what it means to be human will evolve.", "Uncertain"),
    ("Global cooperation will increase to address global challenges.", "Uncertain"),
    ("Resource scarcity will lead to more conflicts.", "Uncertain"),
    ("New forms of energy will be discovered.", "Uncertain"),
    ("The exploration of the deep ocean will reveal new species.", "Uncertain"),
    ("Human longevity will increase significantly.", "Uncertain"),
]
